# This pipeline relies on several environment variables being set in your execution environment.
# Key among these for specifying the input genomic data is:
#
# WGS_ACAF_THRESHOLD_SPLIT_HAIL_PATH:
#   This variable must point to the GCS path of the All of Us ACAF threshold split Hail MatrixTable.
#   Example: gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/acaf_threshold/splitMT/hail.mt
#
# Other required environment variables include:
#   GOOGLE_PROJECT: Your Google Cloud Project ID.
#   WORKSPACE_BUCKET: Your workspace bucket (e.g., gs://fc-secure-...).
#   WORKSPACE_CDR: The BigQuery path to the workspace CDR (e.g., fc-aou-cdr-prod-ct.CYYYYQQRR).
#   CDR_STORAGE_PATH: The GCS path to the CDR storage bucket (e.g., gs://fc-aou-datasets-controlled/v8).

phenotype_definition:
  # Human-readable name for the target phenotype. This name will be
  # utilized in logging, naming of output files, and in generated plots.
  target_name: "Ischemic Stroke"

  # A list of OMOP (Observational Medical Outcomes Partnership) concept IDs.
  # These IDs collectively define the individuals considered as cases for the phenotype.
  concept_ids:
    - 432510
    - 374919